services:
  - type: web
    name: pollpulse-backend
    env: go
    rootDir: backend
    buildCommand: go build -o server ./cmd/server
    startCommand: ./server
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: livepolling
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
